

\chapter{General Discussion and Conclusion}\label{ch:discussion}

\glsresetall[main,acronym]


\yellownote{  This section should give a rough introduction to the themes
   included in the thesis and how the thesis is structured.}

\yellownote{Conclusion section should restate purpose, consolidate research space with a varied array of steps, recommend future research
and cover practical applications, implications or recommendations
}



\yellownote{

Usually the discussion has the following parts:

    It should state the main findings of the study in one or two sentences.
    The discussion should consider the methods, and address possible shortcomings. Defend your answers, if necessary, by explaining both why your answer is satisfactory and why others are not. Only by giving both sides to the argument can you make your explanation convincing.
    Identify potential weaknesses, and comment the relative importance of these to your interpretation of the results and how they may affect the validity of the findings. When identifying limits and weaknesses, avoid using an apologetic tone.
    Support the answers with the results. State why they are acceptable and how they are consistent with previously published knowledge on the topic.
    Discuss any unexpected findings. When discussing an unexpected finding, begin the paragraph with the finding and then describe it.
    Explain how the results and conclusions of this study are important and how they influence our knowledge or understanding of the problem being examined.
    Provide no more than two recommendations for further research. Do not offer suggestions which could have been done within the study, as this shows there has been inadequate examination and interpretation of the data.
}



* The Cochlear Nucleus Stellate Microcircuit

* Optimisation and Modelling of Realistic Microcircuits

* Future Research

\yellownote{
Future Work: 
Don’t view this necessarily as a list of the limitations of your thesis
Think of what you would do if you had an extra year in your Ph.D.
Don’t worry – this is not for your advisor to hold your feet to the fire
Think of 2-3 other follow-on Ph.D. dissertations that you can envision

Conclusions:
Be reflective and honest
What were the lessons learned?
What were the overall insights?
Did you solve the problem completely? How much progress have we made
in your field because of your work
Don’t bore the reader with a cut-and-paste of your Introduction chapter
}


* Conclusion
