

#+LaTeX: \chapter{General Discussion and Conclusion}\label{sec:Discussion}

# \glsresetall[main,acronym]

* The Cochlear Nucleus Stellate Microcircuit Model


\yellownote{Conclusion section should restate purpose, consolidate research space with a varied array of steps, recommend future research
and cover practical applications, implications or recommendations}



# \yellownote{
# Usually the discussion has the following parts:
#     It should state the main findings of the study in one or two sentences.
#     The discussion should consider the methods, and address possible shortcomings. Defend your answers, if necessary, by explaining both why your answer is satisfactory and why others are not. Only by giving both sides to the argument can you make your explanation convincing.
#     Identify potential weaknesses, and comment the relative importance of these to your interpretation of the results and how they may affect the validity of the findings. When identifying limits and weaknesses, avoid using an apologetic tone.
#     Support the answers with the results. State why they are acceptable and how they are consistent with previously published knowledge on the topic.
#     Discuss any unexpected findings. When discussing an unexpected finding, begin the paragraph with the finding and then describe it.
#     Explain how the results and conclusions of this study are important and how they influence our knowledge or understanding of the problem being examined.
#     Provide no more than two recommendations for further research. Do not offer suggestions which could have been done within the study, as this shows there has been inadequate examination and interpretation of the data.
# }


\yellownote{ Restating in the aims of the thesis }
This project was undertaken to design ...... and evaluate .....

\yellownote{Summary of the findings and general implications}
These findings suggest that in general ......
The results of this research support the idea that .......




- CONTRIBUTION TO RESEARCH
These findings enhance our understanding of ......

This research will serve as a base for future studies and ...

The findings from this study make several contributions to the current literature. First,...

The methods used for this X may be applied to other Xs elsewhere in the world.


\yellownote{ Suggesting implications }
 
Evidence from this study suggest that ...

The results of this study indicate that

The results of this research support the idea that ...


\yellownote{Significance and Research contribution}

This research will serve as a base for future studies ...

This model has gone some way towards enhancing our understanding of ...

The present work makes several noteworthy cintributions to ...




\yellownote{ Limitations }

A number of caveats need to be noted regarding the present study.

The most important limitation lies in the fact that ...

The current model was unable to analyse these variables

The current model was not designed to evaluate factors relating to

Our findings in this thess are subject to at lest three limitations.  Firstly, ...

Several limitations of this model need to be acknowledged ...


A number of caveats need to be noted regarding the present study.

The current research was not specifically designed to evaluate factors related to ......

** Recommendations for Future work



** Implications and recommendations for practice and policy

using standard phenomenologically accurate models

using publically available models

replication and reproducibility



* Optimisation Methods and Modelling of Biophysically-Realistic Microcircuits

As mentioned in the literature review, little has been done in replication of
microcircuits and medium sized neural networks from experimental data sets.
Very little was found in the literature on the question of replicating neural
outputs from multiple neurons of different cell-types.  This thesis set out with
the aim of assessing the importance of optimisation in biophysically realistic
neural microcircuits through either sequential or simultaneous methods.

\yellownote{Statements of result with reference to results sections}

The results of genetic algorithm optimisation show/indicate that .......



This experiment did not detect any evidence for ......


* Future Research

\yellownote{Future Work: 
Don’t view this necessarily as a list of the limitations of your thesis.
Think of what you would do if you had an extra year in your Ph.D.
Don’t worry – this is not for your advisor to hold your feet to the fire.
Think of 2-3 other follow-on Ph.D. dissertations that you can envision}


\yellownote{Further studies in simulating effects of blocking specific connections}
Further simulations on the pharmacological effects of GABA and glycine blockers 
\citep{EvansZhao:1998,EvansZhao:1993a,BackoffShadduckEtAl:1999,CasparyBackoffEtAl:1994,PalombiCaspary:1992}
or other modulating neurotransmitters from non-auditory inputs \citep{MuldersPaoliniEtAl:2003}


\yellownote{ CNSM model in ipsi lateral only.  Further studies on commissural inputs?}
Labelled \DS cells project widely to the VCN and  DCN; and in some cases to the contralateral CN in the same manner
\citep{SmithMassieEtAl:2005,ArnottWallaceEtAl:2004}  
In vivo studies have already shown the effects of commisural inhibition of first spike responses to tones
\citep{NeedhamPaolini:2007,NeedhamPaolini:2006,NeedhamPaolini:2003}.

\yellownote{Explore better GA techniques on limited data from multiunit recordings}



* Conclusion

\yellownote{Conclusions: Be reflective and honest. What were the lessons learned? What were the overall insights? Did you solve the problem completely? How much progress have we made
in your field because of your work. Don’t bore the reader with a cut-and-paste of your Introduction chapter.}
