#+title: Discussion and Conclusion
#+AUTHOR: Michael A Eager
#+DATE:
#+LATEX_CLASS: UoM-draft-org-article
#+BIBLIOGRAPHY: ../org-manuscript/bib/MyBib plainnat
#+TODO: REFTEX


#+LaTeX: \chapter{Discussion and Conclusion}\label{sec:FinalChapter}

# \yellownote{
# Usually the discussion has the following parts:
#     It should state the main findings of the study in one or two sentences.
#     The discussion should consider the methods, and address possible shortcomings. Defend your answers, if necessary, by explaining both why your answer is satisfactory and why others are not. Only by giving both sides to the argument can you make your explanation convincing.
#     Identify potential weaknesses, and comment the relative importance of these to your interpretation of the results and how they may affect the validity of the findings. When identifying limits and weaknesses, avoid using an apologetic tone.
#     Support the answers with the results. State why they are acceptable and how they are consistent with previously published knowledge on the topic.
#     Discuss any unexpected findings. When discussing an unexpected finding, begin the paragraph with the finding and then describe it.
#     Explain how the results and conclusions of this study are important and how they influence our knowledge or understanding of the problem being examined.
#     Provide no more than two recommendations for further research. Do not offer suggestions which could have been done within the study, as this shows there has been inadequate examination and interpretation of the data.
# }

\yellownote{This chapter in not complete and will undergo changes.}

* Introduction
:PROPERTIES:
:CUSTOM_ID: sec:FinalChapter:Intro
:END:


This thesis investigated the important physiological mechanisms involved in
neural processing in the stellate microcircuit of the cochlear nucleus. It
focused specifically on rate-place and temporal processing enhancement in the microcircuits
regulating the output of \TS cells. It achieved this through the development and
testing of a novel \CNSM model and methods used to set parameters based on
experimental data. Computer modelling enhances our knowledge of complex neural
interactions in \TS cells and provided further understanding of inputs to higher
centres.  By developing a \BNN with a high degree of realism at the individual
cell level, this thesis has contributed to our understanding of the influence of
synaptic organisation of physiological behaviour in the \CNSM.

This thesis argued that the \BNN models of the \CN or models of
individual cells in the \CNSM have not been sufficiently considerate of the most current physiological
and known experimental data.

To address(overcome) these deficiencies, the thesis presents, develops, and
tests a new model of the CNSM.

It demonstrated through rigorous sequential optimisation that the cell models
and connectivity parameters in the \CNSM model can be created to replicate known
behaviour to tones and noise.  The temporal responses of the optimised \CNSM
model's neurons to AM tones were also investigated.  

Additionally, the thesis
used simultaneous optimisation methods of all network parameters in the CNSM
model using GAs and the sensitivity of parameters given the noise in neural
inputs.  It further developed novel cost functions to condense neural outputs of
a whole network into a single value, which included intracellular responses,
spike times, and time-varying rate.



This chapter concludes the thesis by drawing together the results of the design
and optimisation of the \CNSM model.  It describes the usefulness of the model
as well as the optimisation methods used throughout the thesis.  It reflects on
the implications of the research for the design and optimisation of \BNNs.
Finally it describes the limitations of the research and makes recommendations
for future work arising out of the thesis.

# \yellownote{ Restating in the aims of the thesis }
# This project was undertaken to design ...... and evaluate .....


# This thesis has provided ...
# Through studies of XYZ ..., the thesis has shown that ABC
# I have argued
# I have demonstrated
# I have further developed ..
# Draws together the findings of the design and optimisation of the CNSM model.
# It describes the usefulness of the model as well as the optimisation methods used throughout the thesis.
# It canvasses the limitations of the research and makes recommendations for future work.




 


* Overview of Research Findings 

\yellownote{Summary of the findings and general implications}

These findings suggest that in general ......

The results of this research support the idea that .......

# using standard phenomenologically accurate models

# using publicly available models

# replication and reproducibility


# ------------------
*Chapter \ref{sec:IntroChapter}* identified a range of deficiencies in previous
approaches to modelling and optimisation in the \CN.  
In particular, previous modelling studies of \TS cells and their microcircuit
were limited by their outdated input \AN models, errors in network connectivity
and lack of documentation of parameter optimistation methods.  Additionally,
previous network-based approaches used insufficiently complex neural models that
pre-dated the kinetic current models of \citet{RothmanManis:2003b}.  
These deficiencies limit our insight into neural processing in the CN, and call
for refined model development and optimisation approaches.


# Taken together, 
# To overcome these deficiencies 
# create challenges for getting the best out of BNN models of the auditory system.
# Making increased use 
# - Designed better models and better testing of the models 
# - In particular, the neural cell models used in previous modelling research did not
#  use advances in current models introduced by Rothman and Manis
#  previous modelling research in the CN has not

# AN model deficiencies in previous CN models
# Rothman and Manis highly specialised current models unique to the mammalian VCN
# Use of synaptic connections with sound evidence support
# Demonstration of methods to show how netpwkr parameters were achieved

# introduced the importance of the TS cell and the \CN stellate
# microcircuit to the auditory pathway

# need to create  
# The gap in the literature ... biophysically-realistic models of TS cells and its
# constituent microcircuit (the CNSM) using accurate input models, accurate
# membrane current models


# Chapter \ref{sec:IntroChapter} also introduced the general techniques of
# parameter setting in BNN models.
# Analytical optimisation techniques of spiking neural networks and individual
# current channels are not suitable to BNN models which have large numbers of
# parameters and noisy search spaces.

# Communication of how parameters are discovered/fitted/optimised in BNN models in
# existing models of the CN are limited .

# --------------------
*Chapter \ref{sec:MethodsChapter}* ...
presented the general methods used to create and optimise the CNSM model.
The methods were used to improve the design and development of the CNSM model as a
NEURON package, [[latex:progname][cnstellate]].
This model collates extensive studies in AN models, physiological
 experimentation data at the synapse level and  cell level, and more broadly the
 connectivity across the nuclei into a more realistic model.


# Taken together, the methods introduced in Chapter \ref{sec:MethodsChapter} were
# packaged to form the basis for the \CNSM model.

# The Carney AN model, the Rothman and Manis neural models, and synaptic
# connectivity of the stellate microcircuit were packaged into a NEURON BNN model.


# This included introducing the Carney periphery AN model, membrane current models
# of \citet{RothmanManis:2003b}


#  and its particular version used in this thesis. The Zilany version of the
#  Carney model is most recent detailed model of the AN periphery phenomenological
#  model

# -------------- 
In *Chapter \ref{sec:ModelChapter}*, sequential simple optimisation was used in the
development of cell models and their connectivity in the CNSM model ...


*Chapter \ref{sec:ModelChapter}* developed output responses of each neuron in
 the \CNSM model through rigorous sequential optimisation using simple stimuli.
# and connectivity parameters in the \CNSM model can be created to replicate known
# behaviour to tones and noise.

The \GLG cell model was developed using a novel filter-based neural model due to
the limited intracellular and extracellular data.  Its parameters optimised to
rate-level responses to the only study of known \GCD units
\citep{GhoshalKim:1996}.  \GLG cells are critical to controlling the activity of
granule cells in the GCD, DS and TS cells with increasing sound intensity through
tonic, GABAergic inhibition.


The DS cell model's intrinsic and extrinsic parameters were optimised using
responses to tones, noise and click pairs.  DS cells are known to be wide band,
onset, glycinergic inhibitors of the stellate microcircuit.  Their intracellular
behaviour is characteristic of a coincidence detector and was modelled using the
type I-II RM neural model.  The leak conductance of the model and parameters
controlling synaptic connections from ANF and GLG units were optimised to mimic
the physiological responses of DS cells to tones and noise
\citep{ArnottWallaceEtAl:2004}.  Further optimisation was required to modify the
\GABAa synapse on DS cells to best model the response recovery to click pairs
\citep{BackoffPalombiEtAl:1997}. The role of DS cells in the microcircuit is
primarily as a lateral inhibitor (enhancing rate-place response in TS and TV
cells) but further research has shown the importance of precisely timed phasic
input to enhance temporal output in TS cells.



The TV cell model's synaptic inputs were optimised using rate level curves of
tones and noise to fit the typical type II \DCN unit behaviour
\citep{SpirouDavisEtAl:1999}.  A further optimisation of the offset parameter in
DS cell to TV cell connectivity using notch noise did not confirm the asymmetry
suggested by \citet{ReissYoung:2005}; however the model proposed a different
hypothesis that LSR inputs are the contributor to the asymmetry in type II units
to notch noise.  


TS cells, the main focus of many experimental and modelling studies of the \CN,

 have heterogeneous responses to 
stimuli due to their unique membrane channels (\IKA is not present in any other neurons) and 
variability in synaptic inputs 
(receiving inputs from all other neurons in the microcircuit)


The classification of TS cells into three chopper subtypes using spike-based and
average intracellular responses to tones by \citep{PaoliniClareyEtAl:2005} was
reversed to optimise the \TS cell model and their inputs.

# -------------------
*Chapter \ref{sec:AMChapter}* was an extension of the verification procedures in
Chapter 3 with a focus on responses of the \CNSM model cells to AM tones.
Temporal information in the auditory system is important for animal communications and location of
sounds.  Encoding of temporal information in the AN is through fine-timing of
spikes, phase-locking to the envelope of the stimulus. This poses problems in
loud, noisy and reverberant environments and also in neural transfer.  The
stellate microcircuit is the first step in transforming timing-based temporal
information to a more stable rate-based code in the IC.


The rate and temporal responses of each cell in the CNSM model was investigated
after being presented with AM tones of varying sound intensity and varying
envelope modulation frequency.

In the absence of experimental evidence of GLG cells' response to AM tones, the 
novel GLG cell model proposes that GLG cells diminish timing-information contained in their ANF inputs.
It enforces the hypothesis that GLG cells are purely rate-level encoders and contribute to 
automatic gain mechanisms in the microcircuit.  

Phase-locking in DS cells is greatly enhanced, relative to ANFs, due to collating large numbers of ANF inputs 
and fast intrinsic membrane mechanisms.
The DS cell model's response to AM tones  


Experimental evidence of AM responses in TV cells is inconclusive. ---


The non-linear temporal behaviour of the AN to increasing AM sound intensity shows 

the limitation of the auditory system is exacerbated by encoding of temporal information 

saturation at the IHC-AN synapse 



*Chapter \ref{sec:GAChapter}* ...  reported on the use of GAs and three novel
cost functions on optimising BNN parameters simultaneously.

Real experimental data was substituted for a known BNN target network

It showed the benefits of 


It demonstrated simultaneous optimisation methods of all network parameters in
the CNSM model using GAs and the sensitivity of parameters given the noise in
neural inputs.  It further developed novel cost functions to condense neural
outputs of a whole network into a single value, which included intracellular
responses, spike times, and time-varying rate.





The next part of this chapter brings together the forgoing findings ... 


synthesis of findings and sets out the contributions of the thesis.



* Synthesis and Contributions
:PROPERTIES:
:CUSTOM_ID: sec:LastChapter:Contrib
:END:



** The CNSM Model is an advance in BNN models of the stellate microcircuit

Key statement: The CNSM model is an advance on existing BNN models 


This thesis contributes to the understanding ... 


These findings enhance our understanding of ...



The findings from this study make several contributions to the current literature. First,... 


The methods used for this X may be applied to other Xs elsewhere in the world. 


This research will serve as a basis for future studies ... 


This model has gone some way towards enhancing our understanding of ... 


The present work makes several noteworthy contributions to ...




As mentioned in the literature review, little has been done in replication of
microcircuits and medium sized neural networks from experimental data sets.
Very little was found in the literature on the question of replicating neural
outputs from multiple neurons of different cell types.  This thesis set out with
the aim of assessing the importance of optimisation in biophysically realistic
neural microcircuits through either sequential or simultaneous methods.



good model


fit to experimental data


** Optimisation Methods for BNNs must be shared and explored for reproducibility and integrity
:PROPERTIES:
:CUSTOM_ID: sec:LastChapter:OptBNN
:END:


 Experimental evidence used in optimisation is challenging but Worthwhile


Optimisation methods can provide valuable evidence in developing valid and
reproducible BNN models.


The results of Chapters 3 and 5 show that optimisation techniques ... sequential
or simultaneous methods worthwhile.  


Methodologies 


Tools and practices


The effort to achieve objectives ... create their own kinds of uncertainties.

Limitation and constraints set out in fitness functions ... facilitate ...

Rigorous sequential methods

The results of genetic algorithm
optimisation show/indicate that ...

Simultaneous  -- 



Substantial progression of the use of BNNs in neuroscience ...


Using standard phenomenologically accurate models from inputs to membrane
currents to recognised connections.




Replication and reproducibility is an important factor in numerical modelling
and science in general. Information contained within the compact tables in
Chapters 3 and 4 show the methods for model replication suggested by
\citet{NordlieGewaltigEtAl:2009}.  Reproducibility of simulations is best
performed through using publically available, open source software of the model
and analysis scripts.  




* Limitation of the Research
:PROPERTIES:
:CUSTOM_ID: sec:LastChapter:Limitations
:END:



The specific limitations of the studies in this thesis were canvassed in the
relevant chapters.

The limitations of the CNSM model, described and developed in Chapter 3, relate
to the specificity of the neural models, the exclusion of synaptic connections
without solid foundations, includsion or exclusion of experimental data used in
each optimisation step

A number of caveats need to be noted regarding the present study.

The most important limitation lies in the fact that ...

The current model was unable to analyse these variables

The current model was not designed to evaluate factors relating to

Our findings in this thess are subject to at lest three limitations.  Firstly, ...

Several limitations of this model need to be acknowledged ...


A number of caveats need to be noted regarding the present study.

The current research was not specifically designed to evaluate factors related to ......




* Recommendations for Future Work
:PROPERTIES:
:CUSTOM_ID: sec:LastChapter:FutureWork
:END:


\yellownote{Future Work: 
Don’t view this necessarily as a list of the limitations of your thesis.
Think of what you would do if you had an extra year in your Ph.D.
Don’t worry – this is not for your advisor to hold your feet to the fire.
Think of 2-3 other follow-on Ph.D. dissertations that you can envision}


Fundamental questions about the behaviour of \TS cells remain for exploration
\citep{OertelWrightEtAl:2011}.  Do intrinsic membrane mechanism or network and
synaptic mechanisms play a greater role in the behaviour of \TS cells?  How are
the different categories of \ANFs (\LSR and \HSR) processed by \TS cell
microcircuit?  What are the effects of connections across isofrequency laminae
and how does this effect the spectral representation across the population of
\TS cells?  While answering these questions was beyond the scope of this thesis,
the model and optimisation methods established in the thesis provide valuable
tools for use in those inquiries.

\yellownote{Further studies in simulating effects of blocking specific
connections can be achieved through manipulation of the \CNSM model's
parameters.  Further simulations on the pharmacological effects of GABA and
glycine blockers
\citep{EvansZhao:1998,EvansZhao:1993a,BackoffShadduckEtAl:1999,CasparyBackoffEtAl:1994,PalombiCaspary:1992}
or other modulating neurotransmitters from non-auditory inputs
\citep{MuldersPaoliniEtAl:2003}}


\yellownote{Further studies on commissural inputs?Labelled \DS cells project
widely to the VCN and DCN; and in some cases to the contralateral CN in the same
manner \citep{SmithMassieEtAl:2005,ArnottWallaceEtAl:2004} In vivo studies have
already shown the effects of commisural inhibition of first spike responses to
tones \citep{NeedhamPaolini:2007,NeedhamPaolini:2006,NeedhamPaolini:2003}.}

\yellownote{Explore better GA techniques on limited data from multiunit
recordings.  Explore better GAs or hybrid algorithms that enhance the best
parameters with localised search}



Additionally, enhanced understanding of the complex processing done by the
cochlear nucleus may also contribute to refinement of hearing-impairment
devices.  Further understanding how the processing of sound in noisy
environments works within the network could aid in developing new sound
processing strategies for the cochlear implant and hearing aids.


# This thesis identifies  a number of of priorities for further research.

# bang bang bang xyz


# using standard phenomenologically accurate models

# using publically available models

# replication and reproducibility











 Further development is needed to enhance the robustness of
 the cost function methods to input noise, especially for sensitivity and
 robustness of inhibitory connections in the \CN stellate network.





* Concluding Remarks



In computational neuroscience the development of BNN models is a promising means
by which we can understand highly complex neural processing.  The accuracy of
this understanding relies on the quality of design and optimisation methods used
upon the experimental data.  This thesis presented a novel BNN model of the
cochlear nucleus stellate microcircuit, which was optimised using rigorous
sequential methods and simultaneous genetic algorithms.  The thesis demonstrates
the utility of this approach for BNN models and out understanding of neural
processing.








# \yellownote{Summary of the findings and general implications}
# These findings suggest that in general ......
# The results of this research support the idea that .......


# These findings enhance our understanding of ......

# This research will serve as a base for future studies and ...

# The findings from this study make several contributions to the current literature. First,...

# The methods used for this X may be applied to other Xs elsewhere in the world.


# \yellownote{ Suggesting implications }
 
# Evidence from this study suggest that ...

# The results of this study indicate that

# The results of this research support the idea that ...


# \yellownote{Significance and Research contribution}








# * Conclusion

 \yellownote{Conclusions: Be reflective and honest. What were the lessons
 learned? What were the overall insights? Did you solve the problem completely?
 How much progress have we made in your field because of your work. Don’t bore
 the reader with a cut-and-paste of your Introduction chapter.}

#+BEGIN_LaTeX
  \ifthenelse{\isundefined{\manuscript}}{\newpage\singlespacing\bibliographystyle{plainnat} \bibliography{../org-manuscript/bib/MyBib}\newpage \printglossaries\newpage\listoftodos}{}
#+END_LaTeX
