#+title: Discussion and Conclusion
#+AUTHOR: Michael A Eager
#+DATE:
#+LATEX_CLASS: UoM-draft-org-article
#+BIBLIOGRAPHY: ../org-manuscript/bib/MyBib plainnat
#+TODO: REFTEX


#+LaTeX: \chapter{Discussion and Conclusion}\label{sec:Discussion}

# \yellownote{
# Usually the discussion has the following parts:
#     It should state the main findings of the study in one or two sentences.
#     The discussion should consider the methods, and address possible shortcomings. Defend your answers, if necessary, by explaining both why your answer is satisfactory and why others are not. Only by giving both sides to the argument can you make your explanation convincing.
#     Identify potential weaknesses, and comment the relative importance of these to your interpretation of the results and how they may affect the validity of the findings. When identifying limits and weaknesses, avoid using an apologetic tone.
#     Support the answers with the results. State why they are acceptable and how they are consistent with previously published knowledge on the topic.
#     Discuss any unexpected findings. When discussing an unexpected finding, begin the paragraph with the finding and then describe it.
#     Explain how the results and conclusions of this study are important and how they influence our knowledge or understanding of the problem being examined.
#     Provide no more than two recommendations for further research. Do not offer suggestions which could have been done within the study, as this shows there has been inadequate examination and interpretation of the data.
# }

\yellownote{This chapter in not complete and will undergo severe changes.}

* Introduction
:PROPERTIES:
:CUSTOM_ID: sec:Conc:Into
:END:


This thesis investigated the important physiological mechanisms involved in
neural processing in the \CNSM. It focused specifically on spectral and temporal
enhancement in the microcircuits regulating the output of \TS cells. It achieved
this through the development and testing of a novel \CNSM model and methods used
to set parameters based on experimental data. Computer modelling enhances our
knowledge of complex neural interactions in \TS cells and provided further
understanding of inputs to higher centres.  By developing a \BNN with a high
degree of realism at the individual cell level, this thesis has contributed to
our understanding of the influence of synaptic organisation of physiological
behaviour in the \CNSM.

This thesis argued that the current state of \BNN models of the \CN or models of
individual cells in the \CNSM model was not considerate of the current physiological
and known experimental data.

It demonstrates through rigorous sequential optimisation that the cell models
and connectivity parameters in the \CNSM model can be created to replicate known
behaviour to tones and noise.

Further insight into the temporal 
response optimised \CNSM model's response to 
BNN optimisation  ---






This chapter concludes the thesis by drawing together the results of the design
and optimisation of the \CNSM model.  It describes the usefulness of the model
as well as the optimisation methods used throughout the thesis.  It reflects on
the implications of the research for the design and optimisation of \BNNs.
Finally it describes the limitations of the research and makes recommendations
for future work arising out of the thesis.

# \yellownote{ Restating in the aims of the thesis }
# This project was undertaken to design ...... and evaluate .....


# This thesis has provided ...
# Through studies of XYZ ..., the thesis has shown that ABC
# I have argued
# I have demonstrated
# I have further developed ..
# Draws together the findings of the design and optimisation of the CNSM model.
# It describes the usefulness of the model as well as the optimisation methods used throughout the thesis.
# It canvasses the limitations of the research and makes recommendations for future work.



 


* Overview of Research Findings 
:PROPERTIES:
:CUSTOM_ID: sec:Conc:OverviewRF
:END:

\yellownote{Summary of the findings and general implications}
These findings suggest that in general ......
The results of this research support the idea that .......

using standard phenomenologically accurate models

using publicly available models

replication and reproducibility



*Chapter 1* ...
introduced the importance of the TS cell and the \CN stellate microcircuit to the auditory pathway 

need to create  

The gap in the literature ... biophysically-realistic models of TS cells and its constituent microcircuit (the CNSM) using 
accurate input models, accurate membrane current models 


Chapter 1 also introduced the general techniques of parameter setting in BNN models.

Analytical optimisation techniques of spiking neural networks and individual current channels are not suitable to BNN models which have large numbers of parameters and noisy search spaces.    

Communication of how parameters are discovered/fitted/optimised in BNN models in existing models of the CN are limited .

--------------------
*Chapter 2* ...
presented the general methods used to create and optimise the CNSM model.

This included introducing the Carney periphery AN model, membrane current models of \citet{RothmanManis:2003b}


 and its particular version used in this thesis. The Zilany version of the Carney model is most recent detailed model of the AN periphery phenomenological model 


--------------
In *Chapter 3*, sequential simple optimisation was used in the development of cell models and their connectivity in the CNSM model  ...


Development of a novel filter-based neural model for the \GLG cell, whose input and intrinsic parameters were fitted to the only study of known \GCD units.

The DS cell model, inlcuding its synaptic inputs from ANF and GLG cells, was optimised using responses to tones, noise and click pairs. 


-------------------
*Chapter 4* ...
investigated the output of the optimised CNSM model to AM tones. 



*Chapter 5* ...





The next part of this chapter brings together the forgoing findings ... 


synthesis of findings and sets out the contributions of the thesis.



* Synthesis and Contributions
:PROPERTIES:
:CUSTOM_ID: sec:Conc:Contrib
:END:


This thesis contributes to the understanding ... 


These findings enhance our understanding of ...

The findings from this study make several contributions to the current literature. First,... 


The methods used for this X may be applied to other Xs elsewhere in the world. 


This research will serve as a basis for future studies ... 


This model has gone some way towards enhancing our understanding of ... 


The present work makes several noteworthy contributions to ...




As mentioned in the literature review, little has been done in replication of
microcircuits and medium sized neural networks from experimental data sets.
Very little was found in the literature on the question of replicating neural
outputs from multiple neurons of different cell types.  This thesis set out with
the aim of assessing the importance of optimisation in biophysically realistic
neural microcircuits through either sequential or simultaneous methods.



** The CNSM Model
:PROPERTIES:
:CUSTOM_ID: sec:Conc:CNSM
:END:

good model


fit to experimental data


** Optimisation Methods for BNNs
:PROPERTIES:
:CUSTOM_ID: sec:Conc:OptBNN
:END:


The results of Chapters 3 and 5 show that optimisation techniques ... sequential or simultaneous methods worthwhile. 
The results of genetic algorithm optimisation show/indicate that ...



Substantial progression of the use of BNNs in neuroscience ...




Using standard phenomenologically accurate models from inputs to membrane
currents to recognised connections.




Replication and reproducibility is an important factor in numerical modelling
and science in general. Information contained within the compact tables in
Chapters 3 and 4 show the methods for model replication suggested by
\citet{NordlieGewaltigEtAl:2009}.  Reproducibility of simulations is best
performed through using publically available, open source software of the model
and analysis scripts.  


* Limitation of the Research
:PROPERTIES:
:CUSTOM_ID: sec:Conc:Limitations
:END:


THe specific limitations of the studies

A number of caveats need to be noted regarding the present study.

The most important limitation lies in the fact that ...

The current model was unable to analyse these variables

The current model was not designed to evaluate factors relating to

Our findings in this thess are subject to at lest three limitations.  Firstly, ...

Several limitations of this model need to be acknowledged ...


A number of caveats need to be noted regarding the present study.

The current research was not specifically designed to evaluate factors related to ......




* Recommendations for Future Work
:PROPERTIES:
:CUSTOM_ID: sec:Conc:FutureWork
:END:


\yellownote{Future Work: 
Don’t view this necessarily as a list of the limitations of your thesis.
Think of what you would do if you had an extra year in your Ph.D.
Don’t worry – this is not for your advisor to hold your feet to the fire.
Think of 2-3 other follow-on Ph.D. dissertations that you can envision}


Fundamental questions about the behaviour of TS cells remain for exploration
\citep{OertelWrightEtAl:2011}.  Do intrinsic membrane mechanism or network and
synaptic mechanisms play a greater role in the behaviour of TS cells?  How are
the different categories of \ANFs (\LSR and \HSR) processed by \TS cell
microcircuit?  What are the effects of connections across isofrequency laminae
and how does this effect the spectral representation across the population of
\TS cells?  While answering these questions was beyond the scope of this thesis,
the model and optimisation methods established in the thesis provide valuable
tools for use in those inquiries.

\yellownote{Further studies in simulating effects of blocking specific
connections can be achieved through manipulation of the \CNSM model's
parameters.  Further simulations on the pharmacological effects of GABA and
glycine blockers
\citep{EvansZhao:1998,EvansZhao:1993a,BackoffShadduckEtAl:1999,CasparyBackoffEtAl:1994,PalombiCaspary:1992}
or other modulating neurotransmitters from non-auditory inputs
\citep{MuldersPaoliniEtAl:2003}}


\yellownote{Further studies on commissural inputs?Labelled \DS cells project
widely to the VCN and DCN; and in some cases to the contralateral CN in the same
manner \citep{SmithMassieEtAl:2005,ArnottWallaceEtAl:2004} In vivo studies have
already shown the effects of commisural inhibition of first spike responses to
tones \citep{NeedhamPaolini:2007,NeedhamPaolini:2006,NeedhamPaolini:2003}.}

\yellownote{Explore better GA techniques on limited data from multiunit
recordings.  Explore better GAs or hybrid algorithms that enhance the best
parameters with localised search}



Additionally, enhanced understanding of the complex processing done by the
cochlear nucleus may also contribute to refinement of hearing-impairment
devices.  Further understanding how the processing of sound in noisy
environments works within the network could aid in developing new sound
processing strategies for the cochlear implant and hearing aids.


# This thesis identifies  a number of of priorities for further research.

# bang bang bang xyz


# using standard phenomenologically accurate models

# using publically available models

# replication and reproducibility











 Further development is needed to enhance the robustness of
 the cost function methods to input noise, especially for sensitivity and
 robustness of inhibitory connections in the \CN stellate network.





* Concluding Remarks
:PROPERTIES:
:CUSTOM_ID: sec:Conc:ConcludingRemarks
:END:


In computational neuroscience the development of BNN models is a promising means
by which we can understand highly complex neural processing.  The accuracy of
this understanding relies on the quality of design and optimisation methods used
upon the experimental data.  This thesis presented a novel BNN model of the
cochlear nucleus stellate microcircuit, which was optimised using rigorous
sequential methods and simultaneous genetic algorithms.  The thesis demonstrates
the utility of this approach for BNN models and out understanding of neural
processing.








# \yellownote{Summary of the findings and general implications}
# These findings suggest that in general ......
# The results of this research support the idea that .......


# These findings enhance our understanding of ......

# This research will serve as a base for future studies and ...

# The findings from this study make several contributions to the current literature. First,...

# The methods used for this X may be applied to other Xs elsewhere in the world.


# \yellownote{ Suggesting implications }
 
# Evidence from this study suggest that ...

# The results of this study indicate that

# The results of this research support the idea that ...


# \yellownote{Significance and Research contribution}








# * Conclusion

 \yellownote{Conclusions: Be reflective and honest. What were the lessons learned? What were the overall insights? Did you solve the problem completely? How much progress have we made
 in your field because of your work. Don’t bore the reader with a cut-and-paste of your Introduction chapter.}
