#+TITLE: Thesis Manuscript
#+DATE:
#+AUTHOR: Michael A Eager
#+OPTIONS: toc:nil author:nil H:5 <:t >:t tasks:nil
#+STARTUP: oddeven
#+TODO: REFTEX
#+LANGUAGE: en_GB-ise-wo_accents
#+BIBLIOGRAPHY: MyBib alphanat
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)

#+LaTeX_CLASS: UoM-thesis-org



* My Thesis


## Chapter 1: intro and literature review
#+LaTeX :\cleardoublepage
#+include: ../LiteratureReview/Chapter01.org 

# ## Methods Chapter
#+LaTeX: \cleardoublepage
#+include: ../MethodsChapter/Chapter02.org  


#+BEGIN_LaTeX
   \cleardoublepage\part[Sequential Optimisation of the Cochlear Nucleus Stellate Network]{Sequential Optimisation in the Stellate Microcircuit of the Cochlear Nucleus}
   \psection{Introduction to Part \thepart}
   \yellownote{Small introduction to first part.}
#+END_LaTeX
 
## Chapter 3 without appendix
#+include: ../SimpleResponsesChapter/Chapter03.org 


## Chapter 4 without appendix
#+LaTeX: \clearpage
#+include: ../VowelProcessingChapter/Chapter04.org 

#+BEGIN_LaTeX
  \cleardoublepage
  \part[GA Optimisation]{Simultaneous Optimisation of Realistic Microcircuits using Genetic Algorithms}
          \label{part:2}
  %=========================================================================
  
  \psection{Introduction to Part \thepart}
  
  \glsreset{BNN}
  
  % \PARstart{T}{he studies} 
  The studies in this section evaluated the
  usefulness of genetic algorithms for determining the synaptic parameters of a
  \BNN. This was done by using a model of a microcircuit in the auditory
  brainstem as an example network on which to test the algorithm. First, a
  "target" model was generated with predetermined synaptic parameters. Then
  using the target model, training data of network responses were generated,
  which were then used by the genetic algorithm to estimate the synaptic
  parameters of the target model.  Experimental observables, such as
  extracellular spike times, peri-stimulus time histograms, and intracellular
  voltage waveforms, were used to define the "fitness" functions for
  optimization. The ability of the algorithm to find the known neural parameters
  was assessed for the different fitness functions.
  
  Success of the genetic algorithm optimization was affected by intrinsic
  noise in the network and by the sensitivity of the cost functions to
  changes in each parameter. The results have shown the potential of
  genetic algorithms in constraining the synaptic parameters of \BNNs
  from experimental data.
  
  Section \ref{sec:GA:ResultDiffAN} shows the results for the most
  realistic situation for optimising \BNNs, whereby the inputs and network
  construction were all randomised.  In the
  subsection~\ref{sec:GA:param-sens-results}, the effects of parameter
  permutations were tested to evaluate the responses of each cost function
  and how the GA best genomes were able to perform relative to the
  parameter permutations.
  
  
  \yellownote{Section \ref{sec:GA:ResultIdeal}, deals with an ideal situation of
  optimisation without any noise.  The input spikes are fixed throughout
  the GA optimisation, and the target parameters are able to provide a
  perfect score of 0.  The effects of parameter perturbations were also
  assessed for this situation.}
  
  \yellownote{Section \ref{sec:GA:IndividualSens}, explores the hypothesis that
  individual parameters play a greater role in the optimisation rather
  than thinking of the all the parameters at once.  The local gradients of
  the cost functions around each individual parameter target was evaluated
  and tested for the significant gradients with ideal and different
  inputs.  The best genomes parameter error was then assessed to determine
  whether the local gradients were decisive in the GA optimisation.}
#+END_LaTeX

## Chapter 5
## + LaTeX: \chapter[GA Optimisation]{Simultaneous Optimisation of Microcircuits using Genetic Algorithms}\label{sec:GAChapter}
#+include: ../GAChapter/Chapter05.org 
 

# \cleardoublepage
# \setcounter{tocdepth}{0}
# ## Discussion and Conclusion
#+include:  ./Chapter06.org

## Conclusion
## + include: ./Chapter07.org

#+LATEX:   \end{mainmatter}

# ##
# ## Appendix
# ##
# #+LATEX:   \begin{appendix}
# # Use \chapter{Appendix A}\label{appendixA} in first 
# #+include: ../SimpleResponsesChapter/Chapter03Appendix.org
# # \newpage
# # + include: ../VowelResponsesChapter/Chapter04Appendix.org
# # Optimisation of BNNs using Ideal inputs
# # + include: ../GAChapter/Chapter05B.org :lines "1298-1720"
# # Sensitivity Analysis of Individual Parameters near the Global Optimum
# # + include: ../GAChapter/Chapter05.org :lines "1722-2114"
# #\newpage
# #+include: ../GAChapter/Chapter05Appendix.org
# #+LATEX:   \end{appendix}

##
## Bibliography
##

#+LATEX: \begin{backmatter}
#+LATEX: \chapter*{\bibname}\markboth{\MakeUppercase\bibname}{\MakeUppercase\bibname}
#   %
#   % Uncomment the following line to produce a
#   % bibliography list of all entries in the bib database
#   %\nocite{*}
#   %
#   %bmc_article} % Style BST file
#+LATEX: \bibliographystyle{plainnat}
#+LATEX: \bibliography{../hg/manuscript/bib/MyBib}
#+LATEX: \end{backmatter}



#... and of eight years work! :-)

##DRAFTING
\newpage
\listoftodos


* Prelude                                                          :noexport:

#+name: my-thesis-latex-export
#+begin_src emacs-lisp
    (setq org-latex-to-pdf-process '("pdfquick %f"))
    ;; (setq org-latex-to-pdf-process '("pdflatex -interaction nonstopmode %f" 
    ;;                                  "makeglossaries %b" "bibtex %b" "pdflatex -interaction nonstopmode %f" 
    ;;                                  "pdflatex -interaction nonstopmode %f" )) 
    ;; (setq org-latex-to-pdf-process '("lapdf Chapter3")) 
    (setq org-export-latex-final-hook ())
    (add-hook 'org-export-latex-final-hook
               (lambda ()
                 (goto-char (point-min)) 
                 (search-forward "\\begin{document}") 
                 (push-mark)
                 (replace-regexp "\\( \\|\n\\)\\\\ref" 
                                 "~\\\\ref")
                (goto-char (mark))
                (replace-regexp "\\( \\|\n\\)\\\\citep" 
                                "\\\\ \\\\citep")  
                ;; shorten section titles
                (goto-char (mark))
                (replace-regexp "\\\\section{\\(.*\\):" 
                                "\\\\section[\\1]{\\1:")
                ;; Go back to start
                (goto-char (mark))
                ;; Correct for citations immediately after an item
                (replace-regexp "item[~\\\\]" 
                                "item ")
                ;; Acronyms or Capitals at the end of a sentence cause poor spacing
                (goto-char (mark))
                (replace-regexp "\\([A-Z][A-Z]\\)\\.\\( \\|\n\\)" 
                                "\\1\\\\@. ")
                ;; Double acronyms
                (goto-char (mark))
                (replace-regexp "\\([A-Z][A-Zs]\\) \\([\\\\A-Z]\\)" 
                                "\\1\\\\ \\2")
                ;; Force a space between numbers followed by text or acronym 
                (goto-char (mark))
                (replace-regexp "\\([0-9]\\) \\([\\\\A-Za-z]\\)" 
                                "\\1\\\\ \\2")
                ;; silly repeats corrected
                (goto-char (mark))
                (replace-regexp "\\\\}\\([^{]*\\)\\\\{" 
                                "}\\1{")
                (goto-char (mark))
                (replace-regexp "\\\\{" 
                                "{")
                (goto-char (mark))
                (replace-regexp "\\\\}" 
                                "}")
  ;;        ;; Correct for poor tildas
  ;;      ;                  (goto-char (mark))
  ;;      ;                  (replace-regexp "\\\\~\\{\\}" 
  ;;      ;                                  "~")
  ;;              (goto-char (mark))
  ;;              (replace "^#\\+LATEX_HEADER:.*$" "")
  ;;             (goto-char (mark))
  ;;              (replace-regexp "i\\.e\\. "  "i.e.\\\\ ")
  ;;              (goto-char (mark))
  ;;              (replace-regexp "\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ " "\\\\ ")
                (goto-char (mark))
                (replace-regexp "\\\\section{My Thesis}\n\\\\label{sec-1}" 
                                " ") 
    
               )   )
   (add-to-list 'org-export-latex-classes 
                '("UoM-thesis-org"
  "\%\% -*- mode: latex; mode: tex-fold; TeX-PDF-mode: t; TeX-master t  -*-
   \\documentclass[12pt,a4paper,titlepage,twoside,openright]{book}
   % Use the UniMelb Dissertation Template
   \\usepackage{../hg/manuscript/style/uomthesis}
   % For drafts uncomment the following line
   \\usepackage[light,timestamp,first]{draftcopy}
   % Comment out the following line TO MARK blank pages with the
   % text This page intentionally left blank.
   \\newcommand{\\markblankpages}{}
   % Comment out the following line for the copy submitted to the library
   \\newcommand{\\archivalpapernote}{}
   % User defined commands
   \\usepackage[acronym]{glossaries}
   \\input{../hg/manuscript/misc/glossary}    
   \\input{../hg/manuscript/user-defined}
   \\setcounter{secnumdepth}{5}
   \\makeglossaries
   % \\includeonly{Chapter05}
   % \\hypersetup{ pdftitle = \\myTitle, pdfauthor = Michael A Eager, pdfsubject= PhD thesis, pdfkeywords = auditory system, cochlear nucleus, microcircuit, computational neuroscience, optimisation  }
   \\graphicspath{{../LiteratureReview/gfx/}{../SimpleResponsesChapter/gfx/}{../VowelResponsesChapter/gfx/}{../figures/}{/media/data/Work/cnstellate/golgi/}{/media/data/Work/cnstellate/TV_RateLevel/}{/media/data/Work/cnstellate/}{/media/data/Work/cnstellate/ResponsesNoComp/ModulationTransferFunction/}{../GAChapter/}{../GAChapter/gfx/}{./GAChapter/archive/}}
   \\newcommand{\\manuscript}{}
    [NO-DEFAULT-PACKAGES]
    [NO-PACKAGES]" 
                  ("\n\n\\section{%s}" . "\n\n\\section{%s}")
                  ("\n\n\\subsection{%s}" . "\n\n\\subsection{%s}") 
                  ("\n\n\\subsubsection{%s}" . "\n\\subsubsection{%s}") 
                  ("\n\\paragraph{%s}" . "\n\\paragraph{%s}"))) 
   (setq org-export-latex-title-command "\n
   %% Front matter
   %%
   \\begin{frontmatter}
     \\frontmatterheadings
     % Collect the dissertation information for the title page
      \\input{../hg/manuscript/misc/metadata}
      % Generate the title page
      \\maketitle
      \\input{../hg/manuscript/misc/abstract}
      % Author declaration
      \\makedeclaration
      % Acknowledgements
       \\input{../hg/manuscript/misc/acknowledgements}
      % Preface
      \\input{../hg/manuscript/misc/preface}
      % Dedications...
       \\input{../hg/manuscript/misc/dedication}
      % TOC, LOF, LOT
      {%
              \\singlespacing%
              \\pdfbookmark[1]{\\contentsname}{tableofcontents} 
              \\tableofcontents
              \\pdfbookmark[1]{\\listfigurename}{lof} 
              \\listoffigures%
     % Do not include a list of tables if you have less
     % than 10 tables, as per SGS suggestion.
              \\pdfbookmark[1]{\\listtablename}{lot} 
              \\listoftables
              \\pdfbookmark[1]{Glossary of Terms}{glossary} 
              \\printglossaries
              \\clearpage
        }%
   \\end{frontmatter} 
   \\begin{mainmatter}
  
   \\mainmatterheadings
  ") 
   (setq TeX-master t)
#+end_src

#+RESULTS:
: t






